"""Application-wide constants and enumerations."""

# Time-related constants
MARKET_TIMEZONES = {
    "NSE": "Asia/Kolkata",
    "US": "America/New_York",
}

# Trade types
TRADE_TYPE_LONG = "LONG"
TRADE_TYPE_SHORT = "SHORT"
TRADE_TYPES = {TRADE_TYPE_LONG, TRADE_TYPE_SHORT}

# Trade status
TRADE_STATUS_OPEN = "OPEN"
TRADE_STATUS_CLOSED = "CLOSED"
TRADE_STATUS_PENDING = "PENDING"
TRADE_STATUSES = {TRADE_STATUS_OPEN, TRADE_STATUS_CLOSED, TRADE_STATUS_PENDING}

# Order types
ORDER_TYPE_BUY = "BUY"
ORDER_TYPE_SELL = "SELL"
ORDER_TYPE_SHORT = "SHORT"
ORDER_TYPE_COVER = "COVER"
ORDER_TYPES = {ORDER_TYPE_BUY, ORDER_TYPE_SELL, ORDER_TYPE_SHORT, ORDER_TYPE_COVER}

# Markets
MARKET_NSE = "NSE"
MARKET_US = "US"
SUPPORTED_MARKETS = {MARKET_NSE, MARKET_US}

# Intervals
INTERVAL_1M = "1m"
INTERVAL_5M = "5m"
INTERVAL_15M = "15m"
INTERVAL_1H = "1h"
INTERVAL_1D = "1d"
SUPPORTED_INTERVALS = {INTERVAL_1M, INTERVAL_5M, INTERVAL_15M, INTERVAL_1H, INTERVAL_1D}

# Default values
DEFAULT_STARTING_CAPITAL = 200000.0
DEFAULT_MARKET = MARKET_NSE
DEFAULT_INTERVAL = INTERVAL_5M
DEFAULT_PERIOD = "30d"

# File paths
DEFAULT_STATE_FILE = "trading_state.json"
DEFAULT_CLEAN_CLOSED_TRADES_FILE = "clean_closed_trades.csv"
