"""Framework-independent trading domain models."""

from .models import (
    AssetClass,
    Instrument,
    Order,
    OrderSide,
    OrderStatus,
    OrderType,
    Position,
    PositionSide,
    RiskDecision,
    RiskDecisionStatus,
    Signal,
    SignalSide,
    TradingStatus,
)
from .risk import OrderIntent, RiskContext, RiskEngine, RiskLimits
from .risk_portfolio import PortfolioRiskLimits, PortfolioRiskState, order_key
from .sizing import BrokerConstraints, SizingLimits, SizingResult, size_position
from .portfolio import FillRecord, PortfolioError, PortfolioManager, PositionView
from .execution import (
    PaperAccountingMode,
    PaperAction,
    PaperExecutionError,
    PaperExecutionPolicy,
    PaperExecutor as LegacyPaperExecutor,
    PaperFill,
    PaperPortfolio,
    estimate_paper_charges,
)
from .orders import (
    InvalidOrderTransition as LegacyInvalidOrderTransition,
    OrderManager as LegacyOrderManager,
    OrderSubmissionResult as LegacyOrderSubmissionResult,
)
from .order_management import (
    BrokerRejected,
    IdempotencyConflict,
    InvalidOrderTransition,
    ManagedOrder,
    OrderEvent,
    OrderGateway,
    OrderManager,
    OrderManagerError,
    OrderRequest,
    SubmissionResult,
    new_client_order_id,
)
from .market_session import MarketSession
from .trading_calendar import TradingCalendar
from .brokers import (
    BrokerAccount,
    BrokerAdapter,
    BrokerConfigError,
    BrokerCredentials,
    BrokerDisconnected,
    BrokerError,
    BrokerOrderStatus,
    BrokerPosition,
    BrokerRegistry,
    MarketStatus,
    PaperBroker,
)
from .executors import (
    ExecutionConfigError,
    ExecutionSettings,
    Executor,
    LiveExecutor,
    LiveReadiness,
    LiveTradingRefused,
    PaperExecutor,
    TradingMode,
    create_executor,
    live_trading_failures,
)
from .aggregation import (
    AggregatedAction,
    AggregatedDecision,
    AggregationConfig,
    SignalAggregator,
    SignalInputs,
)
from .strategies import OrbVwapConfig, OrbVwapStrategy, Strategy
from .regime import (
    MarketRegimeEvaluator,
    RegimeAssessment,
    RegimeConfig,
    RegimeLabel,
    RegimeUnavailable,
    regime_score,
)
from .strategy_pipeline import (
    PipelineStatus,
    StrategyPipelineConfig,
    StrategyPipelineResult,
    StrategyResearchPipeline,
)
from .research import ResearchEvidence

__all__ = [
    "AggregatedAction",
    "AggregatedDecision",
    "AggregationConfig",
    "SignalAggregator",
    "SignalInputs",
    "OrbVwapConfig",
    "OrbVwapStrategy",
    "Strategy",
    "MarketRegimeEvaluator",
    "RegimeAssessment",
    "RegimeConfig",
    "RegimeLabel",
    "RegimeUnavailable",
    "regime_score",
    "PipelineStatus",
    "StrategyPipelineConfig",
    "StrategyPipelineResult",
    "StrategyResearchPipeline",
    "ResearchEvidence",
    "AssetClass",
    "Instrument",
    "Order",
    "OrderSide",
    "OrderStatus",
    "OrderType",
    "OrderIntent",
    "OrderManager",
    "LegacyOrderManager",
    "LegacyOrderSubmissionResult",
    "LegacyInvalidOrderTransition",
    "BrokerRejected",
    "IdempotencyConflict",
    "InvalidOrderTransition",
    "ManagedOrder",
    "OrderEvent",
    "OrderGateway",
    "OrderManagerError",
    "OrderRequest",
    "SubmissionResult",
    "new_client_order_id",
    "MarketSession",
    "TradingCalendar",
    "PaperAccountingMode",
    "PaperAction",
    "PaperExecutionError",
    "PaperExecutionPolicy",
    "PaperExecutor",
    "LegacyPaperExecutor",
    "BrokerAccount",
    "BrokerAdapter",
    "BrokerConfigError",
    "BrokerCredentials",
    "BrokerDisconnected",
    "BrokerError",
    "BrokerOrderStatus",
    "BrokerPosition",
    "BrokerRegistry",
    "MarketStatus",
    "PaperBroker",
    "ExecutionConfigError",
    "ExecutionSettings",
    "Executor",
    "LiveExecutor",
    "LiveReadiness",
    "LiveTradingRefused",
    "TradingMode",
    "create_executor",
    "live_trading_failures",
    "PaperFill",
    "PaperPortfolio",
    "PortfolioRiskLimits",
    "PortfolioRiskState",
    "order_key",
    "BrokerConstraints",
    "SizingLimits",
    "SizingResult",
    "size_position",
    "FillRecord",
    "PortfolioError",
    "PortfolioManager",
    "PositionView",
    "estimate_paper_charges",
    "Position",
    "PositionSide",
    "RiskDecision",
    "RiskDecisionStatus",
    "RiskContext",
    "RiskEngine",
    "RiskLimits",
    "Signal",
    "SignalSide",
    "TradingStatus",
]
